name: STAGING - Fake deploy (app)

on:
  push:
    paths:
      - apps/app/**
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Success!"