name: PRODUCTION - Fake deploy (backend)

on:
  push:
    tags: backend-v[1-9]+.[0-9]+.[0-9]+
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Success!"