name: Generate release draft

on:
  workflow_dispatch:
  push:
    branches:
      - main
  # pull_request event is required only for autolabeler
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  # write permission is required to create a github release
  contents: write
  # write permission is required for autolabeler
  # otherwise, read permission is required at least
  pull-requests: write

jobs:
  app:
    name: '[app] Draft release'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-app.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  backend:
    name: '[backend] Draft release'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-backend.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}