name: Test

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: apps/api

jobs:
  deploy_api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set SemVer variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" | sed 's/v//' >> $GITHUB_ENV

      - name: Show vars
        run: |
          echo $GITHUB_REF
          echo $GITHUB_ENV